elimination of comments from June 26
iobox420/crm-for-labels-frontend pull request #4
Opened 2022-06-30 12:34 UTC by iobox420

Идем по замечаниям. 
```
Alexander, [27.06.2022 9:17]
поставь себе в хром redux debugger, если будешь оставлять redux

Alexander, [27.06.2022 9:17]
это лучше, чем консоль логи в редьюсерах ставить
```
Расширение давным давно стоит, спасибо за наводку. 
```
Alexander, [27.06.2022 9:19]
оба @ts-ignore

Alexander, [27.06.2022 9:19]
можешь удалить, если JSON.parse убреешь

Alexander, [27.06.2022 9:22]
[ Photo ]
invalidateQueries возвращает промис

Alexander, [27.06.2022 9:22]
ты можешь его вернуть

Alexander, [27.06.2022 9:22]
onSuccess: () => queryClient.invalidateQueries('admin/get-acts'),

Alexander, [27.06.2022 9:23]
тогда у тебя mutation.isLoading будет true не только пока post запрос грузится, но и пока не зарезолвится промис, которые возвращаешь в onSuccess

Alexander, [27.06.2022 9:23]
собственно лоадер будет на и POST и на GET, что почти всегда нужно поведение
Alexander, [27.06.2022 9:19]
оба @ts-ignore

Alexander, [27.06.2022 9:19]
можешь удалить, если JSON.parse убреешь

Alexander, [27.06.2022 9:22]
[ Photo ]
invalidateQueries возвращает промис

Alexander, [27.06.2022 9:22]
ты можешь его вернуть

Alexander, [27.06.2022 9:22]
onSuccess: () => queryClient.invalidateQueries('admin/get-acts'),

Alexander, [27.06.2022 9:23]
тогда у тебя mutation.isLoading будет true не только пока post запрос грузится, но и пока не зарезолвится промис, которые возвращаешь в onSuccess

Alexander, [27.06.2022 9:23]
собственно лоадер будет на и POST и на GET, что почти всегда нужно поведение

Alexander, [27.06.2022 9:24]
поправь везде // noinspection JSIgnoredPromiseFromCall

Alexander, [27.06.2022 9:24]
// noinspection DuplicatedCode
другие инспекции удали, они не нужны в коде. Люди с другими иде не будут понимать что это вообще за комментарии

Alexander, [27.06.2022 9:26]
[ Photo ]
в webstorm найди в поиске в плагинах import cost
```
Поправил везде onSuccess, привел лямбда функции. Ts-ignore везде убрал. 
Инспекции от ide тоже везде почистил. Расширение import cost поставил - классная штука👍

```
Alexander, [27.06.2022 9:29]
я сам feature-sliced design первый раз вижу, не супер попялрная тема. Потом чекну
```
Пока отказался от такого архитектурного паттерна. 
Сейчас в проекте такая структура 
/app - файлы инициализации приложения
/features - компоненты такие например на таблица с users или artists
/page - страницы
/hoc - компоненты которые возвращают компоненты
/processes - все что связано с взамодействием  с апи и управлением состоянием приложения
/shared - переиспользуемые компоненты такие как 
- таблица которая может принимать различные массивы данных(юзеры, артисты, акты, треки и т.д.)
- кастомный компоненты ячейки в ant table
/widget - error, loading, nothing data  компоненты
```
Alexander, [27.06.2022 9:31]
[ Photo ]
postAct я бы инлийнил первый параметром в useMutation, она же один раз используется
```
Поправил с учетом замечания
```
Alexander, [27.06.2022 9:31]
[ Photo ]
так есть смысл оборачивать только если ты выносишь прям в отдельный файл и переиспользуешь функцию
```
Кастомный хук решил оставить, как то мне проще когда читаешь компоненты сразу понятно что там происходит 

```
Alexander, [27.06.2022 9:35]
удали console.log и debugger строчки в коде
```
Сделано
```
Alexander, [27.06.2022 9:39]
по поводу порядка в котором чекать статусы в react-query

Alexander, [27.06.2022 9:39]
https://tkdodo.eu/blog/status-checks-in-react-query

Alexander, [27.06.2022 9:39]
короткая и хорошая статья

Alexander, [27.06.2022 9:44]
правда в ней нет zero state, как у тебя.

Alexander, [27.06.2022 9:44]
тогда можешь так
const renderSomething = () => {
    if (data.length) {
      return data.map(item => (
          /**/
        )
      );
    }

    if (status === 'loading') {
      return <ActivityIndicator size="large" />;
    }

    if (status === 'error') {
      return <Text>Something went wrong</Text>;
    }

    return <Text>No data</Text>;
}
```
Статью прочитал, поправил порядок с учетом замечаний. 
```
Alexander, [27.06.2022 9:54]
[In reply to Alexander]
dataWithKey, там тебе не нужен индекс массив как ключ, у тебя в элементах массива уже есть уникальный идентификатор
```
Компонент table от antdesign требует key в массиве строк которые ты ей скармливаешь, поэтому я добавляю key. Думаешь стоит это делать на бекенеде?
```
Alexander, [27.06.2022 9:57]
[ Photo ]
статью прочитаешь и не придется typecast через as делать и вопросительные знаки тоже

Alexander, [27.06.2022 9:57]
as тайпкаст не безопасен зачастую. Надо стараться без него
```
Так как теперь делается не 1 большой запрос,а несколько маленьких потребность в as typecast пропала конкретно в таком виде. 
Но все равно есть вопросы по типизации компонентов. Чуть позже напишу подробнее. 
```
Alexander, [27.06.2022 9:58]
JSON.stringify удали, кажется, что нигде не нужен
```
Удалил и поменял статус deleted с boolean на enum у себя в бекенде

```
Alexander, [27.06.2022 10:04]
вообще старайся повыше поднять логику. Я имею в виду максимально данные подготовить прям после того, как с бекенда получил например

Alexander, [27.06.2022 10:04]
чтобы в render'ах уже поменьше логики было и было чисто верстка выглядела

Alexander, [27.06.2022 10:06]
и её лучше собирать в одном месте. Т.е. у тебя например в одном куске кода оборачивается в moment(), а форматирование делается в другом месте.

Alexander, [27.06.2022 10:07]
[ Photo ]
то есть ты можешь, допустим, в этих функциях уже форматированные данные, как тебе удобно
```
Перенес подготовку строк (каст к типам и добавление key) для табличек в сервис. 

```
Возможность передачи данных в camelCase, а не snake_case.
```
 У меня вся база в snake_case запилена и для того что бы визуально поля были одинаковые на фронте и на беке я решил не менять. 
```
Alexander, [27.06.2022 10:07]
[ Photo ]
то есть ты можешь, допустим, в этих функциях уже форматированные данные, как тебе удобно

Alexander, [27.06.2022 10:07]
кстати почему POST для получения данных, а не GET?

Alexander, [27.06.2022 10:09]
а тебе нужен body именно для get запросов

Alexander, [27.06.2022 10:10]
я посмотрел, вроде у тебя параметров мало, мб просто через query params
```
Поменял на query params и о чудо все работает с гет запросом

```
// TS2571: Object is of type 'unknown'.
  if (error) {
    return <Error message={error.response?.data?.message!} />
  }
```
В это кейсе не разобрался как избежать ошибки для error

Можно так 
```
if (error) {
    if (error instanceof Error) {
      return <Error message={error.response?.data?.message!} />
    }
  }
```
Но тогда 
```
TS2339: Property 'response' does not exist on type '{}'.
```
Работаю над этим. Еще вопрос как указывать типы для компонентов которые могут принимать различные типы данных. 

Пробовал вот так
```
export interface ITableEditable<D, C=any>  {
  data: D;
  columns: C;
}

function TableEditablev <ITableEditable> ({ data, columns, count, setPage, pageSize }) { ....
```

```
 <TableEditablev<IUserFull>
              data={data.rows}
              columns={columns}
              count={data.count}
              setPage={setPage}
              pageSize={pageSize}
            />
```
Но опять же не уверен что правильно поступаю. Пошел  читать статью по типизации

По каждому замечанию вроде прошел. Прошу прощения если что то пропустил.

2022-06-30 12:56 UTC, iobox420 commented
Еще переписал users  и artists на react-query

2022-06-30 15:57 UTC, FokinAleksandr requested changes

2022-06-30 15:57 UTC, FokinAleksandr commented on src/features/ActsTable.tsx
>    const { isLoading, error, data } = useActs()
https://bobbyhadz.com/blog/typescript-http-request-axios
```ts
static async getActs(prop: IFkArtistContract) {
  return $api.post<IAct[]>('/admin/get-acts', prop).then(data => data.data)
}
```
у метода можешь return type не указывать, если он сам проставляет то, что нужно. Можешь проверять зажимая cmd/ctrl и мышкой ховер по методу.

2022-06-30 15:57 UTC, FokinAleksandr commented on src/features/ActsTable.tsx
>    const { isLoading, error, data } = useActs()
```tsx
  const { isLoading, isIdle, error, data } = useQuery('admin/get-acts', () =>
    AdminService.getActs({ fk_id_artist_contract: rq.selectedArtistId }),
  )

  if (data && data.length) {
    const columns = Object.keys(data[0]).map(key => {
      return {
        title: key,
        dataIndex: key,
        key: key,
      }
    })
    return (
      <div>
        <Space direction="vertical" size="middle" style={{ display: 'flex', margin: '10px' }}>
          <Card title={'Acts'} size="default">
            <TableEditable data={data} columns={columns} />
            <AddRowButton handle={handleAdd} label={'Add act'} />
          </Card>
        </Space>
      </div>
    )
  }

  if (isLoading || isIdle) return <Loading />
  if (error) return <Error />

  return (
    <div>
      <AddRowButton handle={handleAdd} label={'Add act'} />
      <NothingData />
    </div>
  )
```
В таком порядке лучше возвращать и меньше излишней возни с `!` `?`

2022-06-30 15:57 UTC, FokinAleksandr commented on src/features/ActsTable.tsx
>    const { isLoading, error, data } = useActs()
в `useQuery` можно не дублировать тип, чтобы код не писать лишний раз.

2022-06-30 15:57 UTC, FokinAleksandr commented on src/features/TableEditable.tsx
> +
ну а типы здесь пропишешь?

2022-06-30 16:02 UTC, FokinAleksandr commented
Ошибки с бекенда пользователю не показывай, ему достаточно просто "Упс! Что-то пошло не так." Ошибки бекенда можно пока в консоль для себя логировать, но вообще в проде обычно сторонние сервисы используют, типа сентри, чтобы там все логи смотреть.
```js
if (error) {
  // вот это можно не прокидывать
  return <Error message={error.response?.data?.message!} />
}
```

2022-06-30 16:05 UTC, FokinAleksandr commented
```js
  const dataWithKey = data.map((row, i) => {
    return {
      key: i,
      ...row,
    }
  })
```
лишний код

2022-06-30 16:06 UTC, FokinAleksandr commented on src/features/TableEditable.tsx
> +
Здесь может быть неочевидно. Можешь пока не выносить `<Table>` в отдельный компонент

2022-07-02 08:53 UTC, iobox420 commented on src/features/TableEditable.tsx
> +
Тогда придется 7 раз продублировать один и тот же код.

2022-07-18 15:19 UTC, iobox420 commented
> ```js
>   const dataWithKey = data.map((row, i) => {
>     return {
>       key: i,
>       ...row,
>     }
>   })
> ```
> 
> лишний код

Убрал

2022-07-21 16:03 UTC, FokinAleksandr commented
пройдись по проекту, удали console.log и неиспользуемый файлы. А то неудобно.

2022-07-21 16:04 UTC, FokinAleksandr commented
.sass-cache кажется не должен быть в гите. Добавить в .gitignore

2022-07-21 16:18 UTC, FokinAleksandr requested changes

2022-07-21 16:18 UTC, FokinAleksandr commented on src/shared/castedToTypes.ts
> +  for (let prop in payload) {
так нельзя по ключам объекта ходить, потому что ты можешь лишнее взять. Используй `Object.keys` по дефолту

2022-07-21 16:18 UTC, FokinAleksandr commented on src/shared/castedToTypes.ts
> +function castedToTypes(payload:any) {
тут же просто тип прописать, ты же `IAct` прокидываешь сверху. Но в любом случая эта функция овреинжиниринг. Тебе проще эти 2 свойства вручную привести createdAt, updatedAt

2022-07-21 16:18 UTC, FokinAleksandr commented on package.json
> +    "build-s": "tsc-silent -p './tsconfig.json' --suppress @ && vite build",
а что это? у тебя этого нет в npm пакетах, этот скрипт не выполнится

2022-07-21 16:18 UTC, FokinAleksandr commented on src/features/ActsTable.tsx
> +        fk_id_artist_contract: rq.selectedArtistId!,
это можно из useParams брать, нет смысла из стора.

2022-07-21 16:18 UTC, FokinAleksandr commented on src/features/ActsTable.tsx
> +    return useQuery(['get-acts', page], () =>
в этот массив имеет смысл добавлять все переменные, которые мы снизу используем для запроса, т.е. limit тоже.
потому что если что-то не указать, то react-query не поймет, что мы делаем запрос с другими параметрами и вернет кеш от другого запроса.

2022-07-21 16:18 UTC, FokinAleksandr commented on src/features/ActsTable.tsx
> +  const putActMut = useMutation(ActService.putAct,{
не используй put/post названия в коде. Пиши на англ просто create, update. Потому что библиотеки, технологии могут меняться, лучше называть по смыслу.  Допустим если graphQL вместо rest api, то это неактуальные названия

2022-07-23 15:56 UTC, FokinAleksandr commented on src/processes/models/IActionCreator.ts
> +export interface IActionCreator<T = any> {
он кстати по дефолту по-моему any, если не проставлять через равно

2022-07-23 15:57 UTC, FokinAleksandr commented on src/processes/redux/reactQuerySlice.ts
>  import { createSlice } from '@reduxjs/toolkit'
а для чего все-таки этот слайс?

2022-07-23 15:59 UTC, FokinAleksandr commented on src/processes/redux/reactQuerySlice.ts
>  import { createSlice } from '@reduxjs/toolkit'
я посмотрел, можно удалить. Не используешь же его больше

2022-07-23 15:59 UTC, FokinAleksandr approved these changes

2022-07-25 04:18 UTC, merged